Prep javascript for loops
MattChau01/prep-0922-code-solutions pull request #15
Opened 2022-09-29 06:36 UTC by MattChau01

![prep-javascript-for-loops-1](https://user-images.githubusercontent.com/113082803/192956953-2f5aa967-3135-431f-ad2f-c2f02ac6854c.JPG)
![prep-javascript-for-loops-2](https://user-images.githubusercontent.com/113082803/192956964-a3467451-2b1b-4fb7-bc54-ceaca14fe817.JPG)
![prep-javascript-for-loops-3](https://user-images.githubusercontent.com/113082803/192956971-83266faa-e1d2-43e4-a22f-d62944f85f4c.JPG)

2022-09-29 22:42 UTC, thebearingedge requested changes

2022-09-29 22:42 UTC, thebearingedge commented on prep-javascript-for-loops/main.js
> +}
Please include all three loops in your JS file

2022-09-29 23:01 UTC, MattChau01 reviewed
Updated code

2022-09-30 00:36 UTC, thebearingedge approved these changes

2022-09-30 04:06 UTC, merged